url: '//uptime.bioatlas.se'

mongodb:
  connectionString: mongodb://mongodb/uptime

monitor:
  name:                   origin
  apiUrl:                 '//uptime.bioatlas.se/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  - ./plugins/email
  - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    host: $MAIL_HOST
    port: $MAIL_PORT
#    service:   Gmail # see https://github.com/andris9/Nodemailer/blob/master/lib/wellknown.js for well-known services
    auth:            
      user: $MAIL_USER         # The email account username, e.g. 'username@gmail.com'
      pass: $MAIL_PASS         # The email account password, e.G. 'password'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from: $MAIL_FROM # The message sender, e.g. 'Fred Foo <foo@blurdybloop.com>'
    to: $MAIL_TO # The message recipient, e.g. 'bar@blurdybloop.com, baz@blurdybloop.com'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

basicAuth:
  username:    $USER
  password:    $PASS
verbose: true # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions: 
